apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: tawazun
    name: NouraAlotaibi

spec:

  capacity:
    storage: 2Gi
  volumeModes: Filesystem 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"